In [2]:
import torch

In [8]:
p=torch.tensor([3.,2.,1.,1.])
M1=torch.rand(4,4)
M2=torch.rand(4,3)

In [9]:
p_hom=M1@p

In [10]:
p_hom

tensor([2.1129, 2.0309, 4.4245, 2.4417])

In [41]:
"""
Sample code automatically generated on 2023-08-04 11:37:44

by www.matrixcalculus.org

from input

d/dp M2*(1/sum(m.*p))*M1*p = 1/sum(m.*p)*M2*M1-1/sum(m.*p).^2*M2*M1*p*m'

where

M1 is a matrix
M2 is a matrix
m is a vector
p is a vector

The generated code is provided "as is" without warranty of any kind.
"""

from __future__ import division, print_function, absolute_import

import numpy as np

def fAndG(M1, M2, m, p):
    assert isinstance(M1, np.ndarray)
    dim = M1.shape
    assert len(dim) == 2
    M1_rows = dim[0]
    M1_cols = dim[1]
    assert isinstance(M2, np.ndarray)
    dim = M2.shape
    assert len(dim) == 2
    M2_rows = dim[0]
    M2_cols = dim[1]
    assert isinstance(m, np.ndarray)
    dim = m.shape
    assert len(dim) == 1
    m_rows = dim[0]
    assert isinstance(p, np.ndarray)
    dim = p.shape
    assert len(dim) == 1
    p_rows = dim[0]
    assert M1_cols == M1_rows == M2_cols == p_rows == m_rows

    t_0 = np.dot(m,p)
    t_1 = (1 / t_0)
    t_2 = M1.dot(p)
    t_3 = M2.dot(t_2)
    functionValue = (t_1 * t_3)
    gradient1 = ((t_1 * (M2).dot(M1)) )
    gradient2 = - ((1 / (t_0 ** 2)) * np.outer(t_3, m))
    gradient= gradient1+gradient2
    return functionValue, gradient

def checkGradient(M1, M2, m, p):
    # numerical gradient checking
    # f(x + t * delta) - f(x - t * delta) / (2t)
    # should be roughly equal to inner product <g, delta>
    t = 1E-6
    delta = np.random.randn(4)
    f1, _ = fAndG(M1, M2, m, p + t * delta)
    f2, _ = fAndG(M1, M2, m, p - t * delta)
    f, g = fAndG(M1, M2, m, p)
    print('approximation error',
          np.linalg.norm((f1 - f2) / (2*t) - np.tensordot(g, delta, axes=1)))

def generateRandomData():
    M1 = np.random.randn(4, 4)
    M2 = np.random.randn(3, 4)
    m = M1[3]
    p = np.random.randn(4)
    p[3]=1
    return M1, M2, m, p

if __name__ == '__main__':
    M1, M2, m, p = generateRandomData()
    functionValue, gradient = fAndG(M1, M2, m, p)
    print('functionValue = ', functionValue)
    print('gradient = ', gradient)

    print('numerical gradient checking ...')
    checkGradient(M1, M2, m, p)


functionValue =  [ 4.21774806 -4.80503581  3.77628938]
gradient =  [[-5.97204411  3.12015092  3.63831297 -3.14415717]
 [ 6.95250322 -4.46369239 -5.27597874  4.27274957]
 [-4.21981787  3.64211916  5.59819126 -2.97335674]]
numerical gradient checking ...
approximation error 1.5561059746262898e-09


In [15]:
M1 = np.random.randn(4, 4)

In [16]:
M1[3]

array([-0.72067952, -0.95765738, -0.19412279,  0.402995  ])